package com.project.javasecurityoptimizer.rulepack;

public enum RulePackErrorCode {
    CHECKSUM_MISMATCH,
    SIGNATURE_VERIFICATION_FAILED,
    ENGINE_VERSION_INCOMPATIBLE,
    PERMISSION_OUT_OF_BOUNDS,
    COMPATIBILITY_INCOMPATIBLE,
    RULE_PACK_NOT_FOUND,
    RULE_PACK_NOT_BOUND,
    ENVIRONMENT_LOCK_MISMATCH
}
